# Generated by Django 2.0.3 on 2018-04-13 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('phone_number', models.CharField(max_length=20)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sky_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('diary_date', models.DateField()),
                ('items', models.CharField(max_length=100)),
                ('invoice_sent', models.BooleanField(default=False)),
                ('invoice_paid', models.BooleanField(default=False)),
                ('order_sent', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=40)),
                ('diary_date', models.DateField()),
                ('email_sent', models.BooleanField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Skies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diary_date', models.DateField()),
                ('print_proof', models.ImageField(upload_to='images/')),
                ('watermarked_proof', models.ImageField(upload_to='images/')),
                ('purchases', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='order_items',
            name='order_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.Orders'),
        ),
    ]
